version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing_db
    ports:
      - "6432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: billing
    restart: always
    ports:
      - "7020:7020"
    depends_on:
      - db

networks:
  billing_network:

volumes:
  db-data:
